<h1>Login</h1>
<form method="post">
    <ol>  
        <li>
            <label>
                Email:
                <input type="text" name="email" />
                <?php echo isset($this->errors["email"]) ? $this->errors["email"] : ""; ?>
            </label>
        </li>
        <li>
            <label>
                Password:
                <input type="password" name="password" />
                <?php echo isset($this->errors["password"]) ? $this->errors["password"] : ""; ?>
            </label>
        </li>
        <li>
            <input type="submit" name="login" value="login" />
        </li>
    </ol>
</form>